export const METRICS_DATA = 'METRICS_DATA';
export const CONSOLIDATED_DATA = 'CONSOLIDATED_DATA';
export const FETCH_RECENT = 'FETCH_RECENT';
export const START_POLLING = 'START_POLLING';
export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
